name: Check dir
on:
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check dir
        run: |
          ls -a
